version: "2"
services:
  web:
    build:
        context: .
    image: harbor.k8s.bns.co.kr/leonard0220/springboot
    #image: leonard0220/springboot:v0.0.1
    ports:
      - "8088:8080"
    restart: always
